version: "3.8"

services:
  dance-cup-api-db:
    container_name: dance-cup-api-db
    image: postgres:14-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dance-cup-api
    command: -c log_statement=all

  dance-cup-api:
    container_name: dance-cup-api
    build:
      context: ./
      dockerfile: ./dance-cup-api/Dockerfile
    depends_on:
      - dance-cup-api-db
    ports:
      - 81:80
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
      StorageOptions__ConnectionString: "Host=dance-cup-api-db; Port=5432; Database=dance-cup-api; Username=postgres-user; Password=postgres;"