version: "3.8"

services:
  dance-cup-api-db:
    image: postgres:14-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dance-cup-api
    command: -c log_statement=all

  dance-cup-api:
    build: dance-cup-api/
    ports:
      - 15000:5000
    depends_on:
      - dance-cup-api-db
    command: dotnet ECC.DanceCup.Api.dll
    environment:
      StorageOptions__ConnectionString: "Host=localhost; Port=15432; Database=dance-cup-api; Username=postgres; Password=postgres;"