name: Validate prod

on: [ push, workflow_dispatch ]

jobs:
  test-compose:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Checkout репозиторий
        uses: actions/checkout@v3
      - name: 🐳 Установка Docker Compose (если надо)
        run: sudo apt-get install -y docker-compose
        # 🔴 На ubuntu-latest оно уже есть, можно убрать
      - name: 🚀 Запуск docker-compose
        run: docker-compose -f prod/docker-compose.yml up -d
        # ⚠️ Если что-то не взлетит, workflow всё равно пойдёт дальше. Давай фикс:
      - name: ✅ Проверка состояния контейнеров
        run: docker-compose -f prod/docker-compose.yml up --exit-code-from dance-cup-ui
        # 🔥 Теперь если сервис сдох, весь workflow отвалится
      - name: 🏁 Проверка работы (ждём 10 сек, потом смотрим логи)
        run: |
          sleep 10  # ⚠️ Костыль! Лучше healthcheck или `wait-for-it`
          docker ps
          docker-compose -f prod/docker-compose.yml logs
      - name: 💀 Остановка контейнеров
        if: always()  # 🔥 Теперь даже если что-то упадёт, контейнеры всё равно прибьём
        run: docker-compose -f prod/docker-compose.yml down
      - name: Notify success
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ECC_TG_CHAT_ID }}
        run: |
          MESSAGE="✅ Все образы **prod** окружения **dance-cup** работают корректно"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=MarkdownV2
      - name: Notify failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="❌ Не все образы **prod** окружения **dance-cup** работают корректно"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=MarkdownV2